# Generated by Django 3.2.5 on 2021-07-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210708_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='full_descr',
            field=models.TextField(default='Нужно заполнить описание'),
        ),
        migrations.AddField(
            model_name='event',
            name='short_descr',
            field=models.CharField(default='Имя ивента', max_length=100),
        ),
    ]
