# Generated by Django 3.2.5 on 2021-07-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210708_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Дата окончания события'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Узнавайте у огранизатора', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Дата начала события'),
        ),
    ]
