# Generated by Django 3.2.5 on 2021-07-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210708_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('start_interval', models.DateTimeField(null=True)),
                ('end_interval', models.DateTimeField(null=True)),
                ('topic', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='EventTopics',
            new_name='EventTopic',
        ),
    ]
