# Generated by Django 3.2.5 on 2021-07-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_userfilter_usersearchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearchhistory',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
